name: Create docker container

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 #v2
    
      - name: Run tests
        run: bun test
    
      - name: Setup QEMU
        uses: docker/setup-qemu-action@259a565a6f30a57c28f9ea913f2d359b43ff5fc9 # v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@22b48a429f10e1de233237b5c534c9c3d2e41597 # v4

      - name: Log in to the Container registry
        uses: docker/login-action@946f94de75ea52995b6aa1e54fd3e0aeed6cc573 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3caf19fbe3db1a1a6a8bdce189e09ac0ed35d513 # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build docker container
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4 #v7
        with:
          context: .
          load: true # load into local ci pipeline docker client
          platforms: linux/amd64,linux/arm64 # Also for arm, so it's already cached
          tags: pgbrowser:local
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
      - name: Run trivy for vulnerability scanning
        uses: aquasecurity/trivy-action@bfa4b33a029b9aa80ddb784b45574c30e072c59e # v0.36
        with:
          image-ref: 'pgbrowser:local'
          format: 'table'
          exit-code: '1' # fails if serious vulnerabilities found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

        # build again, but should be way faster since every layer is already cached
      - name: Push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4 #v7
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max